# Generated by Django 6.0.4 on 2026-05-14 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("employee_no", models.CharField(max_length=32)),
                ("user_id", models.BigIntegerField(blank=True, null=True)),
                ("real_name", models.CharField(max_length=64)),
                (
                    "gender",
                    models.SmallIntegerField(
                        blank=True, choices=[(1, "男"), (2, "女")], null=True
                    ),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("id_card", models.CharField(blank=True, default="", max_length=32)),
                ("mobile", models.CharField(blank=True, default="", max_length=20)),
                ("email", models.CharField(blank=True, default="", max_length=128)),
                ("dept_id", models.BigIntegerField(blank=True, null=True)),
                ("position", models.CharField(blank=True, default="", max_length=64)),
                ("entry_date", models.DateField(blank=True, null=True)),
                ("leave_date", models.DateField(blank=True, null=True)),
                (
                    "emp_status",
                    models.SmallIntegerField(
                        choices=[(1, "在职"), (2, "离职"), (3, "试用")], default=1
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("bank_name", models.CharField(blank=True, default="", max_length=64)),
                (
                    "bank_account",
                    models.CharField(blank=True, default="", max_length=64),
                ),
            ],
            options={
                "verbose_name": "员工档案",
                "db_table": "hr_employee",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("attend_date", models.DateField()),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("check_out_time", models.DateTimeField(blank=True, null=True)),
                (
                    "attend_type",
                    models.SmallIntegerField(
                        choices=[
                            (1, "正常"),
                            (2, "迟到"),
                            (3, "早退"),
                            (4, "缺勤"),
                            (5, "请假"),
                            (6, "出差"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "work_hours",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "overtime_hours",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("remark", models.CharField(blank=True, default="", max_length=255)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hr.employee"
                    ),
                ),
            ],
            options={
                "verbose_name": "考勤记录",
                "db_table": "hr_attendance",
                "unique_together": {("employee", "attend_date")},
            },
        ),
        migrations.CreateModel(
            name="Salary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("salary_no", models.CharField(max_length=32, unique=True)),
                ("period", models.CharField(max_length=7)),
                ("base_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "overtime_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "bonus",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "deduction",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "social_security",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "income_tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("gross_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                ("net_salary", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "草稿"), (1, "已审核"), (2, "已发放")], default=0
                    ),
                ),
                ("pay_date", models.DateField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, default="", max_length=500)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hr.employee"
                    ),
                ),
            ],
            options={
                "verbose_name": "薪资单",
                "db_table": "hr_salary",
                "unique_together": {("employee", "period")},
            },
        ),
    ]
