# Generated by Django 6.0.4 on 2026-05-24 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="employee",
            name="dept_id",
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="email",
            field=models.CharField(
                blank=True,
                default="",
                max_length=128,
                validators=[
                    django.core.validators.EmailValidator(message="请输入有效的邮箱地址")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="emp_status",
            field=models.SmallIntegerField(
                choices=[(1, "在职"), (2, "离职"), (3, "试用")], db_index=True, default=1
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="employee_no",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="employee",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="mobile",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="请输入有效的手机号（11位数字，1开头）", regex="^1[3-9]\\d{9}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="salary",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="salary",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "草稿"), (1, "已审核"), (2, "已发放")], db_index=True, default=0
            ),
        ),
    ]
