# Generated by Django 6.0.4 on 2026-05-14 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("parent_id", models.BigIntegerField(default=0, verbose_name="父节点ID")),
                ("perm_name", models.CharField(max_length=64, verbose_name="权限名称")),
                (
                    "perm_code",
                    models.CharField(
                        blank=True, default="", max_length=128, verbose_name="权限标识"
                    ),
                ),
                ("perm_type", models.SmallIntegerField(verbose_name="类型 1目录 2菜单 3按钮")),
                (
                    "path",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="路由路径"
                    ),
                ),
                (
                    "component",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="组件路径"
                    ),
                ),
                ("icon", models.CharField(blank=True, default="", max_length=64)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_visible", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "权限",
                "db_table": "sys_permission",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("role_name", models.CharField(max_length=64, verbose_name="角色名称")),
                (
                    "role_code",
                    models.CharField(max_length=64, unique=True, verbose_name="角色编码"),
                ),
                (
                    "data_scope",
                    models.SmallIntegerField(default=1, verbose_name="数据权限"),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("remark", models.CharField(blank=True, default="", max_length=500)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "角色",
                "db_table": "sys_role",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                (
                    "username",
                    models.CharField(max_length=64, unique=True, verbose_name="账号"),
                ),
                ("real_name", models.CharField(max_length=64, verbose_name="姓名")),
                (
                    "avatar",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="头像"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="邮箱"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="手机号"
                    ),
                ),
                (
                    "dept_id",
                    models.BigIntegerField(blank=True, null=True, verbose_name="部门ID"),
                ),
                ("status", models.BooleanField(default=True, verbose_name="启用状态")),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "last_login_ip",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "db_table": "sys_user",
            },
        ),
        migrations.CreateModel(
            name="RolePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="system.permission",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="system.role"
                    ),
                ),
            ],
            options={
                "db_table": "sys_role_permission",
                "unique_together": {("role", "permission")},
            },
        ),
        migrations.AddField(
            model_name="permission",
            name="roles",
            field=models.ManyToManyField(
                blank=True,
                related_name="permissions",
                through="system.RolePermission",
                to="system.role",
            ),
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="system.role"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "sys_user_role",
                "unique_together": {("user", "role")},
            },
        ),
        migrations.AddField(
            model_name="role",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="roles",
                through="system.UserRole",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
