# Generated by Django 6.0.4 on 2026-05-24 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="permission",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="parent_id",
            field=models.BigIntegerField(
                db_index=True, default=0, verbose_name="父节点ID"
            ),
        ),
        migrations.AlterField(
            model_name="permission",
            name="perm_code",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=128,
                verbose_name="权限标识",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="role",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="status",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="user",
            name="dept_id",
            field=models.BigIntegerField(
                blank=True, db_index=True, null=True, verbose_name="部门ID"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                validators=[
                    django.core.validators.EmailValidator(message="请输入有效的邮箱地址")
                ],
                verbose_name="邮箱",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="请输入有效的手机号（11位数字，1开头）", regex="^1[3-9]\\d{9}$"
                    )
                ],
                verbose_name="手机号",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.BooleanField(db_index=True, default=True, verbose_name="启用状态"),
        ),
    ]
