# Generated by Django 6.0.4 on 2026-05-14 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("parent_id", models.BigIntegerField(default=0)),
                ("account_code", models.CharField(max_length=32)),
                ("account_name", models.CharField(max_length=64)),
                (
                    "account_type",
                    models.SmallIntegerField(
                        choices=[(1, "资产"), (2, "负债"), (3, "权益"), (4, "收入"), (5, "费用")]
                    ),
                ),
                ("balance_dir", models.SmallIntegerField(choices=[(1, "借"), (2, "贷")])),
                ("level", models.SmallIntegerField(default=1)),
                ("is_leaf", models.BooleanField(default=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "会计科目",
                "db_table": "fin_account",
            },
        ),
        migrations.CreateModel(
            name="Payable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("payable_no", models.CharField(max_length=32, unique=True)),
                ("supplier_id", models.BigIntegerField()),
                ("ref_type", models.CharField(blank=True, default="", max_length=32)),
                ("ref_id", models.BigIntegerField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "未付"), (1, "部分付"), (2, "全部付"), (9, "已核销")],
                        default=0,
                    ),
                ),
                ("remark", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "verbose_name": "应付账款",
                "db_table": "fin_payable",
            },
        ),
        migrations.CreateModel(
            name="Receivable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("receivable_no", models.CharField(max_length=32, unique=True)),
                ("customer_id", models.BigIntegerField()),
                ("ref_type", models.CharField(blank=True, default="", max_length=32)),
                ("ref_id", models.BigIntegerField(blank=True, null=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "received_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "未收"), (1, "部分收"), (2, "全部收"), (9, "已核销")],
                        default=0,
                    ),
                ),
                ("remark", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "verbose_name": "应收账款",
                "db_table": "fin_receivable",
            },
        ),
        migrations.CreateModel(
            name="Voucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("voucher_no", models.CharField(max_length=32, unique=True)),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("GENERAL", "记账凭证"),
                            ("RECEIVE", "收款凭证"),
                            ("PAY", "付款凭证"),
                            ("TRANSFER", "转账凭证"),
                        ],
                        default="GENERAL",
                        max_length=16,
                    ),
                ),
                ("voucher_date", models.DateField()),
                ("period", models.CharField(max_length=7)),
                (
                    "total_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[(0, "草稿"), (1, "已审核"), (2, "已过账"), (9, "已作废")],
                        default=0,
                    ),
                ),
                ("ref_type", models.CharField(blank=True, default="", max_length=32)),
                ("ref_id", models.BigIntegerField(blank=True, null=True)),
                ("preparer_id", models.BigIntegerField()),
                ("reviewer_id", models.BigIntegerField(blank=True, null=True)),
                ("review_at", models.DateTimeField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "verbose_name": "财务凭证",
                "db_table": "fin_voucher",
            },
        ),
        migrations.CreateModel(
            name="VoucherItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.IntegerField()),
                ("summary", models.CharField(max_length=255)),
                (
                    "debit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "credit_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.account",
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.voucher",
                    ),
                ),
            ],
            options={
                "verbose_name": "凭证明细",
                "db_table": "fin_voucher_item",
            },
        ),
    ]
