# Generated by Django 6.0.4 on 2026-05-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.SmallIntegerField(
                choices=[(1, "资产"), (2, "负债"), (3, "权益"), (4, "收入"), (5, "费用")],
                db_index=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="account",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="parent_id",
            field=models.BigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name="payable",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="payable",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="payable",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "未付"), (1, "部分付"), (2, "全部付"), (9, "已核销")],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="payable",
            name="supplier_id",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="receivable",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="receivable",
            name="customer_id",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="receivable",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="receivable",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "未收"), (1, "部分收"), (2, "全部收"), (9, "已核销")],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="period",
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name="voucher",
            name="status",
            field=models.SmallIntegerField(
                choices=[(0, "草稿"), (1, "已审核"), (2, "已过账"), (9, "已作废")],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AddIndex(
            model_name="payable",
            index=models.Index(
                fields=["ref_type", "ref_id"], name="fin_payable_ref_typ_baba03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="receivable",
            index=models.Index(
                fields=["ref_type", "ref_id"], name="fin_receiva_ref_typ_9055c3_idx"
            ),
        ),
    ]
