# Generated by Django 6.0.4 on 2026-05-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("warehouse_code", models.CharField(max_length=32, unique=True)),
                ("warehouse_name", models.CharField(max_length=64)),
                (
                    "warehouse_type",
                    models.SmallIntegerField(
                        choices=[(1, "原料仓"), (2, "成品仓"), (3, "在途仓"), (4, "退货仓")],
                        default=1,
                    ),
                ),
                ("manager_id", models.BigIntegerField(blank=True, null=True)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "仓库",
                "db_table": "inv_warehouse",
            },
        ),
        migrations.CreateModel(
            name="StockTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("txn_no", models.CharField(max_length=32, unique=True)),
                (
                    "txn_type",
                    models.CharField(
                        choices=[
                            ("PURCHASE_IN", "采购入库"),
                            ("SALE_OUT", "销售出库"),
                            ("TRANSFER_IN", "调拨入库"),
                            ("TRANSFER_OUT", "调拨出库"),
                            ("ADJUST_IN", "盘盈调整"),
                            ("ADJUST_OUT", "盘亏调整"),
                            ("RETURN_IN", "销售退货入库"),
                            ("RETURN_OUT", "采购退货出库"),
                        ],
                        max_length=32,
                    ),
                ),
                ("ref_type", models.CharField(blank=True, default="", max_length=32)),
                ("ref_id", models.BigIntegerField(blank=True, null=True)),
                ("product_id", models.BigIntegerField()),
                ("sku_id", models.BigIntegerField(blank=True, null=True)),
                ("qty_change", models.DecimalField(decimal_places=4, max_digits=15)),
                ("qty_before", models.DecimalField(decimal_places=4, max_digits=15)),
                ("qty_after", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=15, null=True
                    ),
                ),
                ("operator_id", models.BigIntegerField()),
                ("txn_time", models.DateTimeField()),
                ("remark", models.CharField(blank=True, default="", max_length=255)),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存流水",
                "db_table": "inv_transaction",
            },
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("product_id", models.BigIntegerField()),
                ("sku_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "qty_available",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "qty_reserved",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "qty_in_transit",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "avg_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=15),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "verbose_name": "库存台账",
                "db_table": "inv_stock",
                "unique_together": {("warehouse", "product_id", "sku_id")},
            },
        ),
    ]
