# Generated by Django 6.0.4 on 2026-05-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="stock",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="product_id",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="product_id",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="txn_time",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="stocktransaction",
            name="txn_type",
            field=models.CharField(
                choices=[
                    ("PURCHASE_IN", "采购入库"),
                    ("SALE_OUT", "销售出库"),
                    ("TRANSFER_IN", "调拨入库"),
                    ("TRANSFER_OUT", "调拨出库"),
                    ("ADJUST_IN", "盘盈调整"),
                    ("ADJUST_OUT", "盘亏调整"),
                    ("RETURN_IN", "销售退货入库"),
                    ("RETURN_OUT", "采购退货出库"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="warehouse",
            name="warehouse_type",
            field=models.SmallIntegerField(
                choices=[(1, "原料仓"), (2, "成品仓"), (3, "在途仓"), (4, "退货仓")],
                db_index=True,
                default=1,
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["ref_type", "ref_id"], name="inv_transac_ref_typ_bc242a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stocktransaction",
            index=models.Index(
                fields=["warehouse", "product_id"],
                name="inv_transac_warehou_e89fa7_idx",
            ),
        ),
    ]
