# Generated by Django 6.0.4 on 2026-05-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("customer_code", models.CharField(max_length=64, unique=True)),
                ("customer_name", models.CharField(max_length=128)),
                ("customer_type", models.SmallIntegerField(default=1)),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                (
                    "credit_limit",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "credit_used",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "payment_terms",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("salesperson_id", models.BigIntegerField(blank=True, null=True)),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "客户",
                "db_table": "sal_customer",
            },
        ),
        migrations.CreateModel(
            name="SalesOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("order_no", models.CharField(max_length=32, unique=True)),
                ("salesperson_id", models.BigIntegerField()),
                ("warehouse_id", models.BigIntegerField()),
                ("order_date", models.DateField()),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="CNY", max_length=8)),
                (
                    "total_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "草稿"),
                            (1, "待审批"),
                            (2, "已审批"),
                            (3, "部分发货"),
                            (4, "全部发货"),
                            (5, "已关闭"),
                            (9, "已取消"),
                        ],
                        default=0,
                    ),
                ),
                ("approve_by", models.BigIntegerField(blank=True, null=True)),
                ("approve_at", models.DateTimeField(blank=True, null=True)),
                ("remark", models.CharField(blank=True, default="", max_length=500)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sales.customer"
                    ),
                ),
            ],
            options={
                "verbose_name": "销售订单",
                "db_table": "sal_order",
            },
        ),
        migrations.CreateModel(
            name="Delivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("delivery_no", models.CharField(max_length=32, unique=True)),
                ("warehouse_id", models.BigIntegerField()),
                ("delivery_date", models.DateTimeField()),
                (
                    "logistics_co",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "tracking_no",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "receiver_name",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "receiver_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "receiver_addr",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("status", models.SmallIntegerField(default=0)),
                ("operator_id", models.BigIntegerField()),
                ("remark", models.CharField(blank=True, default="", max_length=500)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="sales.customer"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliveries",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "发货单",
                "db_table": "sal_delivery",
            },
        ),
        migrations.CreateModel(
            name="SalesOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.IntegerField()),
                ("product_id", models.BigIntegerField()),
                ("sku_id", models.BigIntegerField(blank=True, null=True)),
                ("unit_id", models.BigIntegerField()),
                ("qty", models.DecimalField(decimal_places=4, max_digits=15)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "delivered_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("remark", models.CharField(blank=True, default="", max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.salesorder",
                    ),
                ),
            ],
            options={
                "db_table": "sal_order_item",
            },
        ),
    ]
