# Generated by Django 6.0.4 on 2026-05-24 02:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="请输入有效的手机号（11位数字，1开头）", regex="^1[3-9]\\d{9}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                validators=[
                    django.core.validators.EmailValidator(message="请输入有效的邮箱地址")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="receiver_phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="请输入有效的手机号（11位数字，1开头）", regex="^1[3-9]\\d{9}$"
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="DeliveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.BigIntegerField()),
                ("sku_id", models.BigIntegerField(blank=True, null=True)),
                ("unit_id", models.BigIntegerField()),
                ("qty", models.DecimalField(decimal_places=4, max_digits=15)),
                ("remark", models.CharField(blank=True, default="", max_length=255)),
                (
                    "delivery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="sales.delivery",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.salesorderitem",
                    ),
                ),
            ],
            options={
                "db_table": "sal_delivery_item",
            },
        ),
    ]
