# Generated by Django 6.0.4 on 2026-05-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_alter_customer_contact_phone_alter_customer_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="customer",
            name="customer_name",
            field=models.CharField(db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="customer",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="delivery",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="order_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="salesorder",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "草稿"),
                    (1, "待审批"),
                    (2, "已审批"),
                    (3, "部分发货"),
                    (4, "全部发货"),
                    (5, "已关闭"),
                    (9, "已取消"),
                ],
                db_index=True,
                default=0,
            ),
        ),
    ]
