# Generated by Django 6.0.4 on 2026-05-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("order_no", models.CharField(max_length=32, unique=True)),
                ("warehouse_id", models.BigIntegerField()),
                ("buyer_id", models.BigIntegerField()),
                ("order_date", models.DateField()),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("currency", models.CharField(default="CNY", max_length=8)),
                (
                    "total_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "草稿"),
                            (1, "待审批"),
                            (2, "已审批"),
                            (3, "部分收货"),
                            (4, "全部收货"),
                            (5, "已关闭"),
                            (9, "已取消"),
                        ],
                        default=0,
                    ),
                ),
                ("approve_by", models.BigIntegerField(blank=True, null=True)),
                ("approve_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approve_remark",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("remark", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "verbose_name": "采购订单",
                "db_table": "pur_order",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("supplier_code", models.CharField(max_length=64, unique=True)),
                ("supplier_name", models.CharField(max_length=128)),
                ("short_name", models.CharField(blank=True, default="", max_length=64)),
                (
                    "contact_person",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("bank_name", models.CharField(blank=True, default="", max_length=128)),
                (
                    "bank_account",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("tax_no", models.CharField(blank=True, default="", max_length=64)),
                (
                    "payment_terms",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("status", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "供应商",
                "db_table": "pur_supplier",
            },
        ),
        migrations.CreateModel(
            name="PurchaseOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("line_no", models.IntegerField()),
                ("product_id", models.BigIntegerField()),
                ("sku_id", models.BigIntegerField(blank=True, null=True)),
                ("unit_id", models.BigIntegerField()),
                ("qty", models.DecimalField(decimal_places=4, max_digits=15)),
                ("unit_price", models.DecimalField(decimal_places=4, max_digits=15)),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "received_qty",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                ("remark", models.CharField(blank=True, default="", max_length=255)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase.purchaseorder",
                    ),
                ),
            ],
            options={
                "db_table": "pur_order_item",
            },
        ),
        migrations.CreateModel(
            name="PurchaseReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("receipt_no", models.CharField(max_length=32, unique=True)),
                ("warehouse_id", models.BigIntegerField()),
                ("receipt_date", models.DateTimeField()),
                ("operator_id", models.BigIntegerField()),
                ("status", models.SmallIntegerField(default=0)),
                ("remark", models.CharField(blank=True, default="", max_length=500)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="purchase.purchaseorder",
                    ),
                ),
            ],
            options={
                "verbose_name": "采购收货单",
                "db_table": "pur_receipt",
            },
        ),
        migrations.CreateModel(
            name="PurchaseReceiptItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.BigIntegerField()),
                ("sku_id", models.BigIntegerField(blank=True, null=True)),
                ("unit_id", models.BigIntegerField()),
                ("qty", models.DecimalField(decimal_places=4, max_digits=15)),
                ("remark", models.CharField(blank=True, default="", max_length=255)),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchase.purchaseorderitem",
                    ),
                ),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="purchase.purchasereceipt",
                    ),
                ),
            ],
            options={
                "db_table": "pur_receipt_item",
            },
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="purchase.supplier"
            ),
        ),
    ]
