# Generated by Django 6.0.4 on 2026-05-24 04:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchase", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseorder",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="order_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="purchaseorder",
            name="status",
            field=models.SmallIntegerField(
                choices=[
                    (0, "草稿"),
                    (1, "待审批"),
                    (2, "已审批"),
                    (3, "部分收货"),
                    (4, "全部收货"),
                    (5, "已关闭"),
                    (9, "已取消"),
                ],
                db_index=True,
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="purchaseorderitem",
            name="product_id",
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="purchasereceipt",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="purchasereceipt",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="contact_phone",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="请输入有效的手机号（11位数字，1开头）", regex="^1[3-9]\\d{9}$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                max_length=254,
                validators=[
                    django.core.validators.EmailValidator(message="请输入有效的邮箱地址")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="supplier_name",
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
