# Generated by Django 6.0.4 on 2026-05-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("parent_id", models.BigIntegerField(default=0, verbose_name="父分类ID")),
                ("cat_name", models.CharField(max_length=64, verbose_name="分类名称")),
                ("cat_code", models.CharField(blank=True, default="", max_length=64)),
                ("level", models.SmallIntegerField(default=1)),
                ("tree_path", models.CharField(blank=True, default="", max_length=500)),
                ("sort_order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "产品分类",
                "db_table": "prd_category",
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("unit_name", models.CharField(max_length=32, verbose_name="单位名称")),
                (
                    "unit_code",
                    models.CharField(max_length=32, unique=True, verbose_name="单位编码"),
                ),
            ],
            options={
                "verbose_name": "计量单位",
                "db_table": "prd_unit",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                (
                    "product_code",
                    models.CharField(max_length=64, unique=True, verbose_name="产品编码"),
                ),
                ("product_name", models.CharField(max_length=128, verbose_name="产品名称")),
                ("brand", models.CharField(blank=True, default="", max_length=64)),
                (
                    "product_type",
                    models.SmallIntegerField(
                        choices=[(1, "成品"), (2, "原材料"), (3, "半成品"), (4, "服务")],
                        default=1,
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "sale_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "min_stock",
                    models.DecimalField(decimal_places=4, default=0, max_digits=15),
                ),
                (
                    "max_stock",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("image_url", models.CharField(blank=True, default="", max_length=255)),
                ("status", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.category",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品",
                "db_table": "prd_product",
            },
        ),
        migrations.CreateModel(
            name="SKU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_by", models.BigIntegerField(default=0, verbose_name="创建人ID")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_by",
                    models.BigIntegerField(blank=True, null=True, verbose_name="修改人ID"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="修改时间"),
                ),
                ("is_deleted", models.BooleanField(default=False, verbose_name="逻辑删除")),
                ("sku_code", models.CharField(max_length=64, unique=True)),
                ("sku_name", models.CharField(max_length=128)),
                ("spec_json", models.JSONField(blank=True, null=True)),
                ("barcode", models.CharField(blank=True, default="", max_length=64)),
                (
                    "weight",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("status", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skus",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "SKU",
                "db_table": "prd_sku",
            },
        ),
    ]
