# Generated by Django 6.0.4 on 2026-05-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="parent_id",
            field=models.BigIntegerField(
                db_index=True, default=0, verbose_name="父分类ID"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_name",
            field=models.CharField(db_index=True, max_length=128, verbose_name="产品名称"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.SmallIntegerField(
                choices=[(1, "成品"), (2, "原材料"), (3, "半成品"), (4, "服务")],
                db_index=True,
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="sku",
            name="barcode",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="sku",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="sku",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="created_by",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="创建人ID"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="逻辑删除"
            ),
        ),
    ]
